name: .NET Core

on:
  push:
    branches: [ mnh48-trial ]
  pull_request:
    branches: [ mnh48-trial ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build VMagicMirror --configuration Release --no-restore
    - name: Test
      run: dotnet test VMagicMirror --no-restore --verbosity normal
